apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: kube-system
spec:
  repo: https://helm.ngc.nvidia.com/nvidia
  chart: gpu-operator
  targetNamespace: gpu-operator
  createNamespace: true
  valuesContent: |-
    dcgmExporter:
      enabled: true
      serviceMonitor:
        enabled: true         # create the ServiceMonitor CR
        additionalLabels:     # <-- uncomment if your Prometheus
          release: kp-stack   #     looks for this label
    grafana.enabled: true
    toolkit:
      env:
        - name: CONTAINERD_SOCKET
          value: /run/k3s/containerd/containerd.sock
