apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: OnFailure
  containers:
    - name: hello-world
      image: hello-world
      # image: docker.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
      # args: ["nbody", "-gpu", "-benchmark"]
      # args: ["sleep", "inf"]
