apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: mk8s-docs-examples

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: gcr-artifact-secret # Reference the secret
      containers:
        - name: my-app
          image: us-central1-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - containerPort: 8080
